### ISSUE TITLE
Общественный бэкап базы данных

### ISSUE THREAD

**Issue by dobrosketchkun** [nyars-jiten/nyars#5]
У вас замечательная база знаний ( взятая из _открытых_ источников ), при этом уже обновляемая сообществом. Было бы очень плохо если бы вам проект внезапно закрылся (всякое бывает, сами знаете, люди теряют интерес или, там, легальные заковырки, опять же) и эти знания пропали бы втуне. Есть ли какая-то возможность сделать открытой её для скачивания? Хотя бы в виде периодически выкладываемых дампов через торрент?

**Comment by etsune** [comment]
Возможность экспорта обязательно будет, однако планировалось формировать открытый дамп из данных, которые были обработаны/проверены пользователями. Поскольку на данный момент таких статей довольно мало, пока занимаемся реализацией более срочных задач.
