### ISSUE TITLE
Ошибка при импорте словаря в Yomichan

### ISSUE THREAD

**Issue by beatboxvad** [nyars-jiten/nyars#56]
"SyntaxError: Unexpected token in JSON at position X"

Данная ошибка появилась начиная с версии `rev.nyars211102` (Yomichan Settings -> Dictionaries) [версия rev.nyars211101 импортируется нормально, без каких-либо ошибок)

Yomichan 21.9.30.2 (Chrome)
![bandicam 2021-11-09 03-06-14-457](https://user-images.githubusercontent.com/93955125/140843095-29c11acc-1ecd-4ff8-9a8b-2853b6f14c0e.jpg)

**Comment by etsune** [comment]
Спасибо, исправлено

**Comment by beatboxvad** [comment]
Снова появилась эта ошибка. Последняя версия, где этой ошибки нету - rev.nyars211224

В текущей версии `nyars_yomichan_220105` ошибка все ёще есть

**Comment by etsune** [comment]
Сейчас должно быть ок, но это пока что не системное решение

**Comment by etsune** [comment]
Исправлено в обновлении от 07.02.2022
