### ISSUE TITLE
Article minor bugs: empty space, new line etc. 

### ISSUE THREAD

**Issue by etsune** [nyars-jiten/nyars#82]
![image](https://user-images.githubusercontent.com/22329037/180914508-99e3711c-30c4-4eeb-8621-cbe4b6460531.png)
哀

**Comment by etsune** [comment]
![image](https://user-images.githubusercontent.com/22329037/180915499-edcc0a48-2efa-43e5-9baa-db6bf7c6c68b.png)
![image](https://user-images.githubusercontent.com/22329037/180915534-bb36f279-60ec-412e-beb9-2366bb01fc1a.png)

**Comment by sawich** [comment]
![image](https://user-images.githubusercontent.com/10461884/200615314-b1360223-10f9-48e7-b796-848c879d5e4d.png)
![image](https://user-images.githubusercontent.com/10461884/200615369-5ab9e4e3-a247-411b-b06b-fc5e1ee80c2e.png)

@etsune
