### ISSUE TITLE
Основной шрифт и fallaback шрифты

### ISSUE THREAD

**Issue by etsune** [nyars-jiten/nyars#92]
- заменить основной шрифт заголовка на https://fonts.google.com/noto/specimen/Noto+Sans+JP?subset=japanese
- в стилях указать альтернативные шрифты (но не добавлять их в ресурсы): `Sukima Gothic Regular`, `BabelStone Han`, `HanaMin`

**Comment by sawich** [comment]
fixed by 6f650d2a2dd8559aa500d75f0f37fcaee6aa852e
