### ISSUE TITLE
Предложение по улучшению словаря II (Yomichan и .txt)

### ISSUE THREAD

**Issue by capriciouscloud** [nyars-jiten/nyars#98]
Было бы неплохо видеть в словаре отображение слова-источника

Например как в статье https://nyars.org/dict/jp/t69A

В форматах Yomichan и .txt слово-источник не отображается, на примере слова サイバーテロ (версия словаря - nyars_230112.txt)

サイバーテロ
(существительное (общее, нарицательное))
кибертерроризм

**Comment by etsune** [comment]
Слово-источник можно добавить при редактировании значения, внизу есть вкладка для заимствований из других языков
![image](https://user-images.githubusercontent.com/22329037/211950616-0e54eccd-c4c8-4d68-a44a-34ac3a938f87.png)
В бета-версии слово-источник не видно из-за бага, это будет исправлено потом

**Comment by capriciouscloud** [comment]
Упс, я забыл добавить то что это касается версий для Йомичан и .txt (которые скачиваются)

**Comment by etsune** [comment]
Исправлено
